### ISSUE TITLE
[Question] is that possible to filter and return only the right language from backend with GraphQL?

### ISSUE THREAD

**Issue by LeonardoRick** [sanity-io/sanity-plugin-internationalized-array#16]
The documentations says

> Using GROQ filters you can query for a specific language key like so:
> 
> *[_type == "person"] {
>   "greeting": greeting[_key == "en"][0].value
> }

Is that possible to do something similar with GraphQL?

**Comment by SimeonGriggs** [comment]
Unfortunately, not at this time:
https://www.sanity.io/docs/graphql#4c51bb8dc529
