### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by gabrielmaldi** [sanity-io/sanity-plugin-internationalized-array#17]
Is it possible to define a default language, so that the user does not need to click `+ EN`?

i.e. when the document is rendered, get this:

<img width="663" alt="Screenshot 2023-06-12 at 07 29 50" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/3728897/2c3602ea-6bf4-4d1d-b0db-209e365d5506">

instead of this:

<img width="675" alt="Screenshot 2023-06-12 at 07 29 43" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/3728897/a182de02-5c33-439d-9e7c-4db435ae971f">

Thanks!

**Comment by SimeonGriggs** [comment]
Sure, set an `initialValue` on the field:
https://www.sanity.io/docs/initial-value-templates

**Comment by gabrielmaldi** [comment]
Surely I'm missing something, but using:

```ts
defineField({
  name: 'name',
  type: 'internationalizedArrayString',
  title: 'Name',
  initialValue: [{_key: 'en', value: 'hello'}],
})
```

renders:

<img width="651" alt="Screenshot 2023-06-12 at 10 16 47" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/3728897/3f9bcb04-14c7-45a4-b1ce-0c683f879974">

**Comment by gabrielmaldi** [comment]
Great! Just to be clear: my intention is to spare the user of having to click on `EN` on each field, i.e. have every internationalized input pre-rendered for English but without a value. Maybe as a workaround `value: ""` can be used (and that'd be fine with me), but a nicer solution would be to perhaps set `defaultLanguage: "en"` at the document level and have the plugin do the heavy lifting behind the scenes.

Thank you!

**Comment by SimeonGriggs** [comment]
Version 1.7.0 now supports a `defaultLanguages` config setting which will create empty array items for specific languages in new documents.

**Comment by gabrielmaldi** [comment]
Great, thank you!
