### ISSUE TITLE
Using a shared languages state

### ISSUE THREAD

**Issue by phh** [sanity-io/sanity-plugin-internationalized-array#21]
We are currently using objects for translations but for good reasons we are considering moving to arrays and specific this plugin.

In our Studio we have quite a few translatable fields and we would like to limit some clicks and some possible mistakes from our editors.

We see now that it's possible to add a `title` field in `en` and `da`, while adding `da`, `it`, `es` to a description field. Since our editors already know from the start what languages the document should be translated into, it's many click to add x amount of languages to x amount of fields - instead of adding them from the beginning.

If it instead would be possible to have a shared languages across all translatable field with this plugin that would solve our needs better.

Something like adding a shared languages field once (using same UI):
<img width="439" alt="image" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/1304003/a3d0a0ef-73cb-497b-afbd-dedeb51ee9fc">

That then would add the translateable fields:
<img width="404" alt="image" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/1304003/a251a22a-c54c-40ea-ac4d-e3a311454b5b">

**Comment by SimeonGriggs** [comment]
Thanks for this. Yes it's a feature request I'm considering at the moment, to only have those + buttons once at the top of the document and have it effect all arrays.
