### ISSUE TITLE
Translatable string list option

### ISSUE THREAD

**Issue by mikkopaderes-iona** [sanity-io/sanity-plugin-internationalized-array#24]
I may be missing something, but is there a solution for string list option to be translatable?

```javascript
defineField({
  name: 'categories',
  title: 'Categories',
  type: 'string',
  options: {
    // This should be translatable
    list: [
      'Shirts',
      'Shorts',
      'Shoes',
    ]
  }
})
```

**Comment by SimeonGriggs** [comment]
Use the same method [described in this section](https://github.com/sanity-io/sanity-plugin-internationalized-array#creating-internationalized-objects)

```ts
// listType.ts

import { defineType } from "sanity";

export const listType = defineType({
    name: 'list',
    type: 'string',
    options: {list: ['one', 'two', 'three']},
  })
```

Register that to your schema types in `sanity.config.ts`

Then add the custom type to your plugin config:

```ts

internationalizedArray({
  // ...other settings
  fieldTypes: ['list']
})

**Comment by mikkopaderes-iona** [comment]
@SimeonGriggs but that means we get English choices only even for the other languages

**Comment by SimeonGriggs** [comment]
Got it. In that instance, perhaps rethink the content model. If you need "the same value, but in different languages," perhaps the field only needs to be set once, and your consuming applications display the right language value. 

Instead of having the same value set in different languages, independently in separate fields.

**Comment by mikkopaderes-iona** [comment]
Hmm, yes, that would be an alternative approach. Not quite the same experience with the other translatable resources but we could try that if there's no built-in solution. Thanks
