### ISSUE TITLE
Hide "+ Add missing language"?

### ISSUE THREAD

**Issue by oskarengstrom** [sanity-io/sanity-plugin-internationalized-array#25]
While I can see this rather big button being useful in some cases, I have had requests from our users to hide it since it's just taking up valuable space. If a site only has 2 langs and one is currently filled out, for example, there's two buttons doing the same thing 🤷‍♂️

An option to hide this would be great! Or if someone could help me how to target these with css to hide manually?

🙏🏻

**Comment by SimeonGriggs** [comment]
Version [1.8.0](https://github.com/sanity-io/sanity-plugin-internationalized-array/releases/tag/v1.8.0) has a configuration option `buttonAddAll` which can be set to false to hide the "Add missing languages" button

```ts
import {defineConfig} from 'sanity'
import {internationalizedArray} from 'sanity-plugin-internationalized-array'

 export const defineConfig({
  // ...
  plugins: [
    internationalizedArray({
      // ...other config
      buttonAddAll: false // default true
    })
  ]
})
```

**Comment by oskarengstrom** [comment]
I tried updating to 1.8.0 but my inputs suddenly looked very different. See attached image.

Any idea on what might cause this?

![Skärmavbild 2023-07-12 kl  14 12 16](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/117371657/3f02e84d-a3fd-4995-8893-02f08b46674b)

**Comment by SimeonGriggs** [comment]
@oskarengstrom That button should only appear when you have array keys that aren't found in the language configuration. Could you paste your schema for that "Global" field?

**Comment by oskarengstrom** [comment]
Well, I never changed any configurations after bumping version 🤷‍♂️

Sure thing, here's the schema:
```
export default {
  name: 'leadQuizModalPage',
  type: 'document',
  title: 'Lead Quiz Modal Page',
  icon: BookIcon,
  fields: [
    {
      name: 'global',
      type: 'object',
      title: 'Global',
      fields: [
        {
          name: 'closeLabel',
          type: 'internationalizedArrayString',
          title: 'Close Label',
        },
        {
          name: 'title',
          type: 'internationalizedArrayString',
          title: 'Title',
        },
      ],
      options: {
        collapsible: true,
        collapsed: true,
      },
    },
```

**Comment by SimeonGriggs** [comment]
Thanks, and what is your languages config in `sanity.config.ts`?

**Comment by oskarengstrom** [comment]
```
    internationalizedArray({
      languages: [
        {id: 'en', title: 'English'},
        {id: 'de', title: 'German'},
      ],
      defaultLanguages: ['en'],
      fieldTypes: ['string', 'text'],
    }),
```

**Comment by SimeonGriggs** [comment]
Ah thank for that. Think I've found the cause of the issue. Will update this thread with a solution soon.
