### ISSUE TITLE
Internationalized Array String in objects not editable

### ISSUE THREAD

**Issue by appfr3d** [sanity-io/sanity-plugin-internationalized-array#37]
I have a document called `Menu`, and which among other fields has an array of a custom `menuItem` object. In the `menuItem` I have defined the title field as an `internationalizedArrayString` like so:
```tsx
    defineField({
      name: 'title',
      title: 'Title',
      type: 'internationalizedArrayString',
    }),
```

When trying to create new or edit `menuItem`s, it is not possible to add any translations.

![image](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/26167521/c7c76ad1-af3c-4b83-94df-3de11e5f2405)

In my `defineConfig` I have this:

```tsx
    internationalizedArray({
      languages: [
          {id: 'nb', title: 'Norwegian (Bokmål)'},
          {id: 'nn', title: 'Norwegian (Nynorsk)'},
          {id: 'en', title: 'English'},
      ],
      defaultLanguages: ['nb'],
      fieldTypes: ['string', 'url', 'slug'],
      buttonAddAll: true,
      buttonLocations: ['field'],
    }),
```

Any obvious reason why this is happening?

**Comment by selbekk** [comment]
Looks like if you add an `internationalizedArrayString` field type to the document itself, it works as expected. This is because of [this check](https://github.com/sanity-io/sanity-plugin-internationalized-array/blob/main/src/plugin.tsx#L54C47-L54C47), which doesn't check for nested arrays of objects.

It looks like the `flattenSchema` doesn't support iterating through arrays of objects like we do here.

**Comment by selbekk** [comment]
Yep, that's what we did. Hopefully we can avoid it in the future :-)

**Comment by DmitriyMaltsevTakeda** [comment]
I'm having the same problem. 

In my case, there is the following document hierarchy:
document (type `Foo`) -> array of objects (type `Bar`) -> array of objects (type `Baz`)

Objects of type `Baz` have several fields of type `internationalizedArrayString`, and they are not editable (same problem as OP had). 

If I add a hidden field of type `internationalizedArrayString` to `Foo` as suggested be @selbekk, it works. 
If I do the same for `Bar` only, the error still reproduces.

I briefly looked at the [fix](https://github.com/sanity-io/sanity-plugin-internationalized-array/pull/40), and it seems that it can handle only the case with one level of nesting in root documents, but I may be wrong. 

Is there any way to fix that without the hidden `internationalizedArrayString` field workaround?
