### ISSUE TITLE
Internationalized Array String still not editable if existing instance does not exist

### ISSUE THREAD

**Issue by iyanushow** [sanity-io/sanity-plugin-internationalized-array#48]
**Describe the bug**

When using an internationalized string field in an array field, the field is uneditable and says `This internationalized field currently has no translations.`

This issue has been reported previously here #37 and appears to have been fixed #40, but it still exists for me on the latest release

**Expected behavior**

When you add an `internationalizesArrayString` field to an array component, the field should allow you add translations

**Screenshots**
<img width="1077" alt="Screenshot 2023-11-01 at 22 32 18" src="https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/62676042/eeeb8d92-e22c-4067-a0b4-de099f03e365">

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

```
@sanity/cli (global)                   3.19.0 (up to date)
@sanity/document-internationalization   2.0.1 (up to date)
@sanity/eslint-config-studio            2.0.4 (latest: 3.0.1)
@sanity/icons                           2.4.1 (latest: 2.6.0)
@sanity/scheduled-publishing            1.2.1 (up to date)
@sanity/ui                              1.7.8 (latest: 1.8.3)
@sanity/vision                         3.19.0 (up to date)
sanity                                 3.19.0 (up to date)

sanity-plugin-internationalized-array 1.10.3
```

**What operating system are you using?**

**Which versions of Node.js / npm are you running?**
`node v18.16.1`

**Comment by fvieira** [comment]
This happened to me too, first field I thought to try this on was a nested one, couldn't figure out why I couldn't add languages until I say @bobinska-dev workaround: https://github.com/sanity-io/sanity-plugin-internationalized-array/issues/37#issuecomment-1662392111
