### ISSUE TITLE
styled-components missmatch

### ISSUE THREAD

**Issue by ciruz** [sanity-io/sanity-plugin-internationalized-array#52]
Hey when using the latest Sanity, Sanity Presentation (which is part of the core Sanity Studio) requires `styled-components@^6.1.1`  while ``sanity-plugin-internationalized-array`` requires `styled-components@^5.3.6`. 

![image](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/987947/30864f05-45d4-4f18-a475-4cfa5734f8e8)

**Comment by SimeonGriggs** [comment]
This should be resolved in recent updates to Presentation
