### ISSUE TITLE
Is it possible to use Sanity client in asynchronous function for loading language list?

### ISSUE THREAD

**Issue by alexanderkalachev** [sanity-io/sanity-plugin-internationalized-array#6]
If yes, what would be the function?
I'm trying something like: 
```
async () => {
    client.fetch(query, params)
        .then(data => {
            const result = data[0].languages;
            return result;
        });
}
```
But it return a promise as a language list instead of an array.

**Comment by SimeonGriggs** [comment]
It is, in the section about [loading languages there is an async example](https://github.com/sanity-io/sanity-plugin-internationalized-array#loading-languages). The function here actually has the client as the first param so it could be:

```js
languages: async (client) => {
  const response = await client.fetch(`*[_type == "language"]{ id, title }`)
  return response
}
```

**Comment by SimeonGriggs** [comment]
I have updated the readme example in #11, re-open this if you still cannot get this feature to work.
