### ISSUE TITLE
Unable to use internationalizedArrayText

### ISSUE THREAD

**Issue by kosjak95** [sanity-io/sanity-plugin-internationalized-array#61]
**Describe the bug**
It is not possible to add _internationalizedArrayText_. After registering the field type in sanity.config.ts and try to use it in my field it throws an runtime exception realted to _textInputRepresentationStyle_

No difference if I will try use defined type 'text' in _fieldTypes_ or try to hack it with creating my own type with text inside, if only it contains text it is not able to create it after opening the internationalized field value.

**To Reproduce**

1. internationalizedArray({
      languages: [
  {id: 'da', title: 'Danish'},
  {id: 'en', title: 'English'}
],
      defaultLanguages: ['da'],
      fieldTypes: ['string', 'text'],
    })

2. defineField({
            name: 'content',
            type: 'internationalizedArrayText',
            title: 'Content',
        })
3. try to insert content.

**Expected behavior**

The internationalized array of texts render, open and be able to consume text.

**Screenshots**
![image](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/38251276/ce5e4366-f49e-43a7-b575-c78edc682832)

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.

@sanity/cli (global)          3.23.1 (latest: 3.28.0)
@sanity/eslint-config-studio   3.0.1 (up to date)
@sanity/vision                3.23.1 (latest: 3.28.0)
sanity                        3.23.1 (latest: 3.28.0)

**What operating system are you using?**
windows

**Which versions of Node.js / npm are you running?**
Node.js v18.12.1.
yarn 1.22.19

**Comment by SimeonGriggs** [comment]
Unable to reproduce, are you using the latest version of the Studio and plugin?
