### ISSUE TITLE
Validation for translatable fields?

### ISSUE THREAD

**Issue by notflip** [sanity-io/sanity-plugin-internationalized-array#64]
**Is your feature request related to a problem? Please describe.**
Is it possible to validate the entry of a translated field? For example:

- One translation needs to be present?
- All translations need to be present?

**Describe the solution you'd like**
Having `validation: (Rule) => Rule.required(),` work on the `internationalizedArrayString` field

**Comment by SimeonGriggs** [comment]
Sure, add validation to the top level array item, you can even return item-specific paths with an error message.

![Screenshot 2024-03-18 at 15 11 48](https://github.com/sanity-io/sanity-plugin-internationalized-array/assets/9684022/eaa7e0dc-3171-48d9-9c6f-4441c96caf52)

```ts
    defineField({
      name: 'title',
      type: 'internationalizedArrayString',
      description: `Catch the reader's eye. Use fewer than 5 words.`,
      validation: (rule) =>
        rule.custom<{value: string; _type: string; _key: string}[]>((value) => {
          if (!value) {
            return 'Title is required'
          }

          const invalidItems = value.filter((item) => item.value.length > 5)

          if (invalidItems.length) {
            return invalidItems.map((item) => ({
              message: `Title "${item.value}" is too long. Must be 5 words or fewer.`,
              path: [{_key: item._key}, 'value'],
            }))
          }

          return true
        }),
    }),
```

**Comment by SimeonGriggs** [comment]
Added this example to the Readme now too :)

https://github.com/sanity-io/sanity-plugin-internationalized-array?tab=readme-ov-file#validation-of-individual-array-items

**Comment by notflip** [comment]
Beautiful, thanks! @SimeonGriggs I'm loving Sanity so far, certainly so with this nice way of handling translations

**Comment by fvieira** [comment]
@SimeonGriggs Your suggestion works, but I can't seem to see the error message inline in the field (with the icon, like with normal validations), the field is just red and the message is only in the validations sidebar. Should open a new issue for this?

**Comment by meatcar** [comment]
@fvieira you can return multiple paths to show the error places.

**Comment by fvieira** [comment]
Thank you @meatcar, I'll test it out next time I use this plugin.
